### ISSUE TITLE
Migrate Specs deployments to Netlify

### ISSUE THREAD

**Issue by abernix** [apollographql/specs#6]
This not only moves us to Netlify to be aligned with the site deployment pattern employed by our other repositories in the Apollo organization and remove this outlier, but it fixes our trailing slash problem in https://github.com/apollo-specs/apollo-specs.github.io/pull/3.

## Steps

- [x] Land https://github.com/apollo-specs/core/pull/7
  - [x] Merge into `v0.1` branch on that repo.
  - [x] Wait like 20 seconds, then verify that https://specs.apollo.dev/jesse-test/core/v0.1/ works
- [x] Land https://github.com/apollo-specs/join/pull/10
  - [x] Merge into `v0.1` branch on that repo.
  - [x] Wait like 20 seconds, then verify that https://specs.apollo.dev/jesse-test/join/v0.1/ works
- [x] Land https://github.com/apollo-specs/apollo-specs.github.io/pull/5, wait a few seconds
  - [x] Test [`https://apollo-specs.netlify.app/`](https://apollo-specs.netlify.app/) to make sure it proxies transparently.
  - [x] Test [`https://apollo-specs.netlify.app/core/v0.1`](https://apollo-specs.netlify.app/core/v0.1)  to make sure it proxies transparently.
  - [x] Test [`https://apollo-specs.netlify.app/core/v0.1/`](https://apollo-specs.netlify.app/core/v0.1/) (trailing slash) to make sure it proxies transparently.
  - [x] Test [`https://apollo-specs.netlify.app/join/v0.1`](https://apollo-specs.netlify.app/join/v0.1) to make sure it proxies transparently.
  - [x] Test [`https://apollo-specs.netlify.app/join/v0.1/`](https://apollo-specs.netlify.app/join/v0.1/) (trailing slash) to make sure it proxies transparently.
- [x] Swap out the `specs.apollo.dev` domain's DNS to point to the `apollo-specs` Netlify deployment.  It will become the primary domain for the `apollo-specs.netlify.app` domain by the end of this process.  **This will incur a small amount of downtime while the domain is in-between properties on Netlify** (I do not think it's worth a more advanced setup to avoid it, even if I can easily imagine one).  _A PR has been created on `monorepo` and has been referenced on this GitHub page; see references in the timeline below._
   - I propose / I would do:
       * Manually changing the DNS TTL for `specs.apollo.dev` to a low TTL - 5 seconds.
         The link to do this is in the `monorepo` PR.
       * Waiting 300 seconds for that TTL to propagate.
       * Change the DNS from a CNAME to `apollo-website-router` to `apollo-specs`.
       * Remove the domain from `apollo-website-router` Netlify app [here](https://app.netlify.com/sites/apollo-website-router/settings/domain).
       * Immediately add it to `apollo-specs` Netlify app [here](https://app.netlify.com/sites/apollo-specs/settings/domain)
       * Set it as the default domain for the `apollo-specs` deployment. (Same link as previous)
         * Wait for TLS certificate re-provisioning for `specs.apollo.dev` (On bottom of previous page, TLS section)
       * Land the PR in `monorepo` that makes this permanent. _(again, PR is created and linked to this PR already.)_
- [x] After everything is confirmed working, delete [all of these lines](https://github.com/apollographql/website-router/blob/1be97afc902e718f29bb27e1bf09a85b2989e6af/_redirects#L45-L50) fro `website-router`
      _(PR has been created on `apollo-website-router` and has been referenced on this GitHub page; see references in the timeline below)_
- [x] Delete https://github.com/apollo-specs/join/blob/main/.github/workflows/push-gh-pages.yml, no longer necessary. (https://github.com/apollo-specs/join/pull/11)
- [x] Delete https://github.com/apollo-specs/core/blob/main/.github/workflows/push-gh-pages.yml, no longer necessary (https://github.com/apollo-specs/core/pull/8)
- [x] Disable GitHub pages on this repository

## Follow-up 
- [x] Transfer all repositories in this organization to `apollographql`
- [x] Rename `apollo-specs.github.io` to just `specs`
- [x] Re-link the GitHub repositories in Netlify for each:
  - [x] https://app.netlify.com/sites/apollo-specs/settings/deploys
  - [x] https://app.netlify.com/sites/apollo-specs-core/settings/deploys
  - [x] https://app.netlify.com/sites/apollo-specs-join/settings/deploys
- [x] Consider / plan a conversion to Gatsby (with `specs-md` as a plugin, most likely)
      Opened issue #7

**Comment by glasser** [comment]
Thanks for doing this.

I think the specs site is currently low profile enough that incurring short downtimes is fine (as is moving expediently on this project with post-merge review if that helps due to timing).

**Comment by abernix** [comment]
@hwillson @glasser Ok, here goes.

**Comment by abernix** [comment]
@hwillson @glasser It should be working in its new configuration right now if either of you wanted to pop it open and test it, but it appears good to me from my tests.

**Comment by hwillson** [comment]
Everything is working well on my side @abernix - thanks for tackling all of this!

**Comment by abernix** [comment]
Ok I've migrated these spec repos to:

* https://github.com/apollographql/specs/
* https://github.com/apollographql/specs-core/
* https://github.com/apollographql/specs-join/

I thought `specs` made sense for the top-level repo, but I wavered on choosing `specs-core` vs `spec-core` and `specs-join` vs `spec-join`.  I went with having `specs-` (instead of `spec-`) prefixes. 🤷
